version: '3.4'
services:
  core_api_db:
    image: postgres
    environment:
      - POSTGRES_DB=signatures-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    ports:
      - '5434:5432'
    command: postgres -c listen_addresses='*'
volumes:
  postgres:
  pgadmin: