version: "3.8"

services:
  signatures_db:
    image: postgres
    environment:
      - POSTGRES_DB=signatures-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - "./data/postgres_signatures:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    command: postgres -c listen_addresses='*'
    networks:
      - signatures

  api:
    build:
      context: .
    command: sh -c "npm run db:seed & npm run start:prod"
    environment:
      - DB_HOST=signatures_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - JWT_SECRET=some-jwt-secret
      - SIGNATURES_DATABASE_URL=postgres://postgres:password@signatures_db:5433/signatures-db
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - signatures_db
    networks:
      - signatures

networks:
  signatures:
